name: rpi_i2c
version: 0.4.0
description: rpi_i2c is a Dart library for using I2C on the Raspberry Pi.
homepage: https://github.com/danrubel/rpi_i2c.dart

# This package only works with Linux running on Raspberry Pi
platforms:
  linux:
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  ffi: ^1.2.1
  path: '>=1.0.0 <2.0.0'
dev_dependencies:
  grinder: ^0.9.0
  pedantic: 1.11.1
  test: ^1.17.0
