name: rpi_i2c
version: 0.3.0
author: Dan Rubel <danrubel@google.com>
description: rpi_i2c is a Dart library for using I2C on the Raspberry Pi.
homepage: https://github.com/danrubel/rpi_i2c.dart
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  path: '>=1.0.0 <2.0.0'
dev_dependencies:
  grinder: ^0.9.0
  pedantic: 1.11.1
  test: ^1.17.0
