name: rpi_i2c
version: 0.1.0
author: Dan Rubel <danrubel@google.com>
description: rpi_i2c is a Dart library for using I2C on the Raspberry Pi.
homepage: https://github.com/danrubel/rpi_i2c.dart
environment:
  sdk: '>=2.0.0-dev.60.0 <3.0.0'
dependencies:
  path: '>=1.0.0 <2.0.0'
dev_dependencies:
  grinder: ^0.8.0
  test: ^1.2.0
