#!/bin/sh
#
# Typically, this script is run by calling
#
#    pub global run rpi_i2c:build_native
#
# See README for setup instructions

# exit on error
set -e

cd $(dirname $0)
echo building rpi_i2c in `pwd`

####################################################################
# Build rpi_i2c native library

g++ -fPIC -c rpi_i2c_ext.cc
# use --no-undefined to check for missing libraries
gcc -shared -lpthread -Wl,-soname,librpi_i2c_ext.so -o librpi_i2c_ext.so rpi_i2c_ext.o

# Copy the library
cp librpi_i2c_ext.so ../../librpi_i2c_ext.so

# echo "exported symbols"
# nm -g ../../librpi_i2c_ext.so | grep ' T '

echo "gcc build complete"
